###### Importing library

In [15]:
import numpy as np

###### Value

In [16]:
sudoku = [[0,0,0,3,0,2,0,0,0],
          [0,5,0,7,9,8,0,3,0],
          [0,0,7,0,0,0,8,0,0],
          [0,0,8,6,0,7,3,0,0],
          [0,7,0,0,0,0,0,6,0],
          [0,0,3,5,0,4,1,0,0],
          [0,0,5,0,0,0,6,0,0],
          [0,2,0,4,1,9,0,5,0],
          [0,0,0,8,0,6,0,0,0]]

##### Print Value

In [17]:
print(sudoku)

[[0, 0, 0, 3, 0, 2, 0, 0, 0], [0, 5, 0, 7, 9, 8, 0, 3, 0], [0, 0, 7, 0, 0, 0, 8, 0, 0], [0, 0, 8, 6, 0, 7, 3, 0, 0], [0, 7, 0, 0, 0, 0, 0, 6, 0], [0, 0, 3, 5, 0, 4, 1, 0, 0], [0, 0, 5, 0, 0, 0, 6, 0, 0], [0, 2, 0, 4, 1, 9, 0, 5, 0], [0, 0, 0, 8, 0, 6, 0, 0, 0]]


##### Convert it into Array

In [18]:
sudoku_matrix = np.matrix(sudoku)

##### Print Sudoku matrix value

In [19]:
print(sudoku_matrix)

[[0 0 0 3 0 2 0 0 0]
 [0 5 0 7 9 8 0 3 0]
 [0 0 7 0 0 0 8 0 0]
 [0 0 8 6 0 7 3 0 0]
 [0 7 0 0 0 0 0 6 0]
 [0 0 3 5 0 4 1 0 0]
 [0 0 5 0 0 0 6 0 0]
 [0 2 0 4 1 9 0 5 0]
 [0 0 0 8 0 6 0 0 0]]


##### Function for number position

In [20]:
def number(y, x, n):
  global sudoku
  for i in range(0, 9):
    if sudoku[y][i] == n:
      return False
  for i in range(0, 9):
    if sudoku[i][x] == n:
      return False
  x0 = (x // 3)*3
  y0 = (y // 3)*3
  for i in range(0, 3):
    for j in range(0, 3):
      if sudoku[y0+i][x0+j] == n:
        return False
  return True

##### Checking function 'number'


In [21]:
number(2, 4 ,1)

False

##### Function for result

In [22]:
def result():
  global sudoku
  for y in range(9):
    for x in range(9):
      if sudoku[y][x] == 0:
        for n in range(1, 10):
          if number(y, x, n):
            sudoku[y][x] = n
            result()
            sudoku[y][x] = 0
        return
  print(np.matrix(sudoku))

##### Print the 'result' function

In [23]:
result()

[[6 8 9 3 4 2 5 1 7]
 [1 5 2 7 9 8 4 3 6]
 [3 4 7 1 6 5 8 9 2]
 [9 1 8 6 2 7 3 4 5]
 [5 7 4 9 3 1 2 6 8]
 [2 6 3 5 8 4 1 7 9]
 [4 9 5 2 7 3 6 8 1]
 [8 2 6 4 1 9 7 5 3]
 [7 3 1 8 5 6 9 2 4]]
